# Generated by Django 6.0.2 on 2026-05-04 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="email_otp",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="email_otp_created_at",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="email_verified",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="password_reset_token",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="password_reset_token_created_at",
        ),
    ]
